services:
  trade-demo-journey-tests:
    build: .
    platform: linux/amd64 # Ensure compatibility with Mac x64 emulation
    environment:
      BROWSERSTACK_USER: ${BROWSERSTACK_USER}
      BROWSERSTACK_KEY: ${BROWSERSTACK_KEY}
      PUBLISH_TEST_RESULTS: 0
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
